<a href="https://colab.research.google.com/github/LCODER2007/Aomide_myval/blob/main/Agricultural_yield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("samuelotiattakorah/agriculture-crop-yield")

print("Path to dataset files:", path)
import pandas as pd

Path to dataset files: /root/.cache/kagglehub/datasets/samuelotiattakorah/agriculture-crop-yield/versions/1

In [24]:
df= pd.read_csv(path+"/crop_yield.csv")
df.head()

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

In [25]:
print(df.dtypes)
numeric_only = df.select_dtypes(exclude=['object']).columns
print(numeric_only)

Region                     object
Soil_Type                  object
Crop                       object
Rainfall_mm               float64
Temperature_Celsius       float64
Fertilizer_Used              bool
Irrigation_Used              bool
Weather_Condition          object
Days_to_Harvest             int64
Yield_tons_per_hectare    float64
dtype: object
Index(['Rainfall_mm', 'Temperature_Celsius', 'Fertilizer_Used',
       'Irrigation_Used', 'Days_to_Harvest', 'Yield_tons_per_hectare'],
      dtype='object')

In [26]:
print(df.isnull().sum())

Region                    0
Soil_Type                 0
Crop                      0
Rainfall_mm               0
Temperature_Celsius       0
Fertilizer_Used           0
Irrigation_Used           0
Weather_Condition         0
Days_to_Harvest           0
Yield_tons_per_hectare    0
dtype: int64

In [27]:
df=df.dropna()
df

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251
...,...,...,...,...,...,...,...,...,...,...
999995,West,Silt,Rice,302.805345,27.987428,False,False,Sunny,76,1.347586
999996,South,Chalky,Barley,932.991383,39.661039,True,False,Rainy,93,7.311594
999997,North,Peaty,Cotton,867.362046,24.370042,True,False,Cloudy,108,5.763182
999998,West,Silt,Wheat,492.812857,33.045505,False,False,Sunny,102,2.070159
999999,West,Sandy,Maize,180.936180,27.298847,True,False,Sunny,76,2.937243

In [28]:
print(df.duplicated().sum())

0

In [29]:
df['Fertilizer_Used']= df['Fertilizer_Used'].astype(int)
df['irrigation_Used']= df['Irrigation_Used'].astype(int)

In [30]:
df['Fertilizer_Used']

0         0
1         1
2         0
3         0
4         1
         ..
999995    0
999996    1
999997    1
999998    0
999999    1
Name: Fertilizer_Used, Length: 1000000, dtype: int64

In [31]:
df.columns

Index(['Region', 'Soil_Type', 'Crop', 'Rainfall_mm', 'Temperature_Celsius',
       'Fertilizer_Used', 'Irrigation_Used', 'Weather_Condition',
       'Days_to_Harvest', 'Yield_tons_per_hectare', 'irrigation_Used'],
      dtype='object')

In [32]:
df=pd.get_dummies(df, columns=['Region', 'Soil_Type', 'Crop','Weather_Condition'], drop_first=True)

In [33]:
df.drop_duplicates(inplace=True)

In [34]:
print(df.info)
print(df.head)

<bound method DataFrame.info of         Rainfall_mm  Temperature_Celsius  Fertilizer_Used  Irrigation_Used  \
0        897.077239            27.676966                0             True
1        992.673282            18.026142                1             True
2        147.998025            29.794042                0            False
3        986.866331            16.644190                0             True
4        730.379174            31.620687                1             True
...             ...                  ...              ...              ...
999995   302.805345            27.987428                0            False
999996   932.991383            39.661039                1            False
999997   867.362046            24.370042                1            False
999998   492.812857            33.045505                0            False
999999   180.936180            27.298847                1            False

        Days_to_Harvest  Yield_tons_per_hectare  irrigation_Used  \
0                   122                6.555816                1
1                   140                8.527341                1
2                   106                1.127443                0
3                   146                6.517573                1
4                   110                7.248251                1
...                 ...                     ...              ...
999995               76                1.347586                0
999996               93                7.311594                0
999997              108                5.763182                0
999998              102                2.070159                0
999999               76                2.937243                0

        Region_North  Region_South  Region_West  ...  Soil_Type_Peaty  \
0              False         False         True  ...            False
1              False          True        False  ...            False
2               True         False        False  ...            False
3               True         False        False  ...            False
4              False          True        False  ...            False
...              ...           ...          ...  ...              ...
999995         False         False         True  ...            False
999996         False          True        False  ...            False
999997          True         False        False  ...             True
999998         False         False         True  ...            False
999999         False         False         True  ...            False

        Soil_Type_Sandy  Soil_Type_Silt  Crop_Cotton  Crop_Maize  Crop_Rice  \
0                  True           False         True       False      False
1                 False           False        False       False       True
2                 False           False        False       False      False
3                  True           False        False       False      False
4                 False            True        False       False      False
...                 ...             ...          ...         ...        ...
999995            False            True        False       False       True
999996            False           False        False       False      False
999997            False           False         True       False      False
999998            False            True        False       False      False
999999             True           False        False        True      False

        Crop_Soybean  Crop_Wheat  Weather_Condition_Rainy  \
0              False       False                    False
1              False       False                     True
2              False       False                    False
3               True       False                     True
4              False        True                    False
...              ...         ...                      ...
999995         False       False                    False
999996         False       False                     True
999997         False       False                    False
999998         False        True                    False
999999         False       False                    False

        Weather_Condition_Sunny
0                         False
1                         False
2                          True
3                         False
4                         False
...                         ...
999995                     True
999996                    False
999997                    False
999998                     True
999999                     True

[1000000 rows x 22 columns]>
<bound method NDFrame.head of         Rainfall_mm  Temperature_Celsius  Fertilizer_Used  Irrigation_Used  \
0        897.077239            27.676966                0             True
1        992.673282            18.026142                1             True
2        147.998025            29.794042                0            False
3        986.866331            16.644190                0             True
4        730.379174            31.620687                1             True
...             ...                  ...              ...              ...
999995   302.805345            27.987428                0            False
999996   932.991383            39.661039                1            False
999997   867.362046            24.370042                1            False
999998   492.812857            33.045505                0            False
999999   180.936180            27.298847                1            False

        Days_to_Harvest  Yield_tons_per_hectare  irrigation_Used  \
0                   122                6.555816                1
1                   140                8.527341                1
2                   106                1.127443                0
3                   146                6.517573                1
4                   110                7.248251                1
...                 ...                     ...              ...
999995               76                1.347586                0
999996               93                7.311594                0
999997              108                5.763182                0
999998              102                2.070159                0
999999               76                2.937243                0

        Region_North  Region_South  Region_West  ...  Soil_Type_Peaty  \
0              False         False         True  ...            False
1              False          True        False  ...            False
2               True         False        False  ...            False
3               True         False        False  ...            False
4              False          True        False  ...            False
...              ...           ...          ...  ...              ...
999995         False         False         True  ...            False
999996         False          True        False  ...            False
999997          True         False        False  ...             True
999998         False         False         True  ...            False
999999         False         False         True  ...            False

        Soil_Type_Sandy  Soil_Type_Silt  Crop_Cotton  Crop_Maize  Crop_Rice  \
0                  True           False         True       False      False
1                 False           False        False       False       True
2                 False           False        False       False      False
3                  True           False        False       False      False
4                 False            True        False       False      False
...                 ...             ...          ...         ...        ...
999995            False            True        False       False       True
999996            False           False        False       False      False
999997            False           False         True       False      False
999998            False            True        False       False      False
999999             True           False        False        True      False

        Crop_Soybean  Crop_Wheat  Weather_Condition_Rainy  \
0              False       False                    False
1              False       False                     True
2              False       False                    False
3               True       False                     True
4              False        True                    False
...              ...         ...                      ...
999995         False       False                    False
999996         False       False                     True
999997         False       False                    False
999998         False        True                    False
999999         False       False                    False

        Weather_Condition_Sunny
0                         False
1                         False
2                          True
3                         False
4                         False
...                         ...
999995                     True
999996                    False
999997                    False
999998                     True
999999                     True

[1000000 rows x 22 columns]>

In [38]:
x=df.drop(columns=['Yield_tons_per_hectare'])
y=df['Yield_tons_per_hectare']

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
print(f"Training size:{x_train.shape}, Test size:{x_test.shape}")

Training size:(800000, 21), Test size:(200000, 21)

In [66]:
from xgboost import XGBRegressor as RandomForest
from sklearn.model_selection import GridSearchCV
params={
    'n_estimators': [100, 200, 300],
    'max_depth': [6, 10, 20],
    'learning_rate': [0.01, 0.05, 0.08],
    'subsample': [0.7, 0.8, 0.9],
    'random_state': [42]
}

model = RandomForest(n_estimators=100, max_depth=10, learning_rate=0.05, subsample=0.8, random_state=42)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [67]:
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test, y_pred)
r2= r2_score(y_test, y_pred)

print(f"Mean_Absolute_Error:{mae:.4f}")
print(f"Mean_Squared_Error:{mse:.4f}")
print(f"R^2:{r2:.4f}")

Mean_Absolute_Error:0.4009
Mean_Squared_Error:0.2524
R^2:0.9124